### ISSUE TITLE
Opt-Out Request - Stardust Labs

### ISSUE THREAD

**Issue by catter1** [IMB11/Loqui#7]
I hereby request that Terralith, Incendium, Nullscape, Structory, Structory: Towers, Continents, and Amplified Nether are removed from your project, as well as any future Stardust Labs project. (I didn't see Continents or Amplified Nether in there - there isn't anything to translate for those mods - but wanted to list them regardless).

We have our own translation effort, and I don't appreciate a new one being started without asking us. While I like the general concept of this mod, I am in belief that it should be opt-in rather than opt-out. Alternatively, at least notify/ask the mod devs of which you wish to have translations for.

(I would have joined your Discord to ask directly, but I am currently out of server spaces)

**Comment by IMB11** [comment]
Thanks for letting me know!

We dont use an opt-in system as it defeats the purpose of Loqui, which is to provide translations for all mods, regardless of owner requirements. As Loqui is still a beta project, we dont have all the features available, such as the ability for authors/mod developers to download any translations users have created (through a web dashboard and gradle plugin)

Yes, we may not be able to check if all the mods have an existing translation effort, but Loqui already does a pretty good job of excluding any existing languages that exist in the mod jar.

**Comment by IMB11** [comment]
Please provide the namespaces (assets/<namespace/lang/...) for the mods you have listed, or you can pull request them yourself into the following file: https://github.com/IMB11/Loqui/blob/master/src/api/src/blacklist.ts

**Comment by IMB11** [comment]
I cannot opt you out unless you're willing to provide the namespaces of these mods. Reopen the issue when you've gathered them.

Marking stale.

**Comment by catter1** [comment]
Apologies, somehow did not get the notification for the initial request.

`terralith`, `incendium`, `nullscape`, `structory`, `structory_towers`, `continents` (doubt it's there), `amplified_nether` (doubt it's there)

**Comment by IMB11** [comment]
Done, see 5b815f39c7524cc2130eea3a80e7f00b3234d6a7
